import Foundation

class Constants {
    static let SETTINGS_BUNDLE_ID = "com.apple.Preferences"
    static let SPRINGBOARD_BUNDLE_ID = "com.apple.springboard"
    static let DOCUMENT_BUNDLE_ID = "com.apple.DocumentsApp"
    static let MEDIA_BUNDLE_ID = "com.lambdatest.MediaApp"
    static let PHOTOS_BUNDLE_ID = "com.apple.mobileslideshow"
    static let CHROME_BUNDLE_ID = "com.google.chrome.ios"
    static let WALLET_BUNDLE_ID = "com.apple.Passbook"
    static let SAFARI_BUNDLE_ID = "com.apple.mobilesafari"
    static let PHONE_BUNDLE_ID = "com.apple.mobilephone"
    
    static let SIGN_OUT = "Sign Out"
    static let DELETE_CONTACT = "Delete Contact"
    static let IGNORE_ALL = "Ignore All"
    static let MY_CARD = "My Card"
    static let EDIT = "Edit"
    static let CONTACTS = "Contacts"
    static let APPLE_ID_ICLOUD_APP_STORE = "Apple ID, iCloud"
    static let APPLE_ACCOUNT_ICLOUD_AND_MORE = "Apple Account, iCloud"
    static let APPLE_ID_PASSWORD = "Apple ID Password"
    static let KEEP_A_COPY = "Keep a copy of your data on this"
    static let SIGN_IN_TO_YOUR_IPHONE = "Sign in to your iPhone"
    static let SIGN_INTO_YOUR_IPHONE = "Sign into your iPhone"
    static let SIGN_IN_TO_ACCESS_YOUR_ICLOUD = "Sign in to access your iCloud data"
    static let IPAD_PRIMARY_APPLE_ACCOUNT = "com.apple.settings.primaryAppleAccount"
    static let IPAD_SETTINGS_WIFI = "com.apple.settings.wifi"
    static let PHOTOS_APP_BUTTON = "PhotosSidebarButton"
    static let AIRPLANE_MODE = "Airplane Mode"
    static let AEROPLANE_MODE = "Aeroplane Mode"
    static let AIRPLANE_MODE_IPAD = "com.apple.settings.airplaneMode"
    static let WI_FI = "Wi-Fi"
    static let WLAN = "WLAN"
    static let Bluetooth = "Bluetooth"
    static let WI_FI_SWITCH = "Wi-Fi Switch"
    static let MULTITASKING = "Multitasking"
    static let ONEAPPATATIME = "OneAppAtATime"
    static let SETTINGS = "Settings"
    static let NOTIFICATIONS = "Notifications"
    static let SETTINGS_NOTIFICATIONS = "com.apple.settings.notifications"
    static let NOTIFICATIONS_OFF = "Notifications Off"
    static let ALLOW_NOTIFICATION = "Allow Notifications"
    static let DONT_ALLOW = "Don't Allow"
    
    static let NEVER = "Never"
    static let AUTO_LOCK = "Auto-Lock"
    static let LARGER_TEXT = "Larger Text"
    static let DEFAULT = "Default"
    
    static let TEXT_SIZE = "Text Size"
    static let LIGHT = "Light"
    static let DISPLAY_AND_BRIGHTNESS = "Display & Brightness"
    
    static let REMOVE = "Remove"
    static let CANCEL = "Cancel"
    static let DELETE = "Delete"
    
    static let LARGER_ACCESSIBILITY_SIZES = "Larger Accessibility Sizes"
    static let DISPLAY_TEXT_SIZE = "Display & Text Size"
    static let SMART_INVERT = "Smart Invert"
    static let CLASSIC_INVERT = "Classic Invert"
    static let ACCESSIBILITY = "Accessibility"
    
}
